name: Go

on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Get
      run: go get -v github.com/tdewin/mysql-employees
    - name: Install
      run: go install -v github.com/tdewin/mysql-employees
    - name: Upload the binary
      uses: actions/upload-artifact@v2.2.3
      with:
        name: "mysql-employees"
        path: "/home/runner/go/bin/mysql-employees"
